import './globals.css'
import 'react-tooltip/dist/react-tooltip.css'
import { ToastContainer, Flip } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className='h-[100vh]'>
                <ToastContainer draggableDirection="x" pauseOnFocusLoss={false} transition={Flip} />
                {children}
            </body>
        </html>
    )
}
